[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm install"
]

[phases.build]
cmds = [
  "npm run prod",
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
