[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Packages.zip"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
